all: part1 part2
part1:
	@echo ---------------Part1-----------------
	@gcc part1.c -o test1
	@./test1
	@rm -f test1
part2:
	@echo ---------------Part2-----------------
	@gcc part2.c -o test2
	@./test2
	@rm -f test2