all: echo

echo:
	@echo "please enter make part1, make part2, or make part3"

part1:
	@gcc part1.c -o test
	@./test
	@rm -f test
part2:
	@gcc part2.c -o test
	@./test
	@rm -f test
part3:
	@gcc part3.c -o test
	@./test
	@rm -f test

