all: clear compile run clean

clean:
	@rm -f test1

	@rm -f test3
compile: 
	@gcc part1.c -o test1

	@gcc part3.c -o test3
	
run:
	@./test1
	@echo ----------part1 end--------------
	@./test3
	@echo ----------part3 end--------------
		
clear:
	clear
